<?php
declare(strict_types=1);

require __DIR__ . '/_bootstrap.php';

// Public HTML card for VK link preview.
// Reads snapshot.json generated by publish_preview.php or schedule_preview.php.
// Uses signed publish_image_public.php as og:image.

$sid = (string)($_GET['sid'] ?? '');
if (!preg_match('~^[a-zA-Z0-9_-]{3,64}$~', $sid)) {
    http_response_code(400);
    echo 'Bad sid';
    exit;
}

// --- вычисляем PRIVATE_DIR без констант ---
$WWW_DIR     = dirname(__DIR__, 3);          // .../data/www
$PRIVATE_DIR = $WWW_DIR . '/_private';       // .../data/www/_private

$dir = $PRIVATE_DIR . '/tournament/published/' . $sid;

$snapFile = $dir . '/snapshot.json';
if (!is_file($snapFile)) {
    http_response_code(404);
    echo 'Not found';
    exit;
}

$snap = json_decode((string)file_get_contents($snapFile), true);
if (!is_array($snap)) {
    http_response_code(500);
    echo 'Bad snapshot';
    exit;
}

$title  = (string)($snap['title'] ?? 'LazaCup');
$text   = (string)($snap['text'] ?? '');
$images = $snap['images'] ?? [];

$cover = '';
if (is_array($images) && count($images) > 0 && is_array($images[0])) {
    $cover = (string)($images[0]['file'] ?? '');
}
if ($cover === '') {
    http_response_code(404);
    echo 'No image';
    exit;
}

$publicExp = (int)($snap['public_exp'] ?? 0);
$publicSig = (string)($snap['public_sig'] ?? '');
if ($publicExp <= time() || $publicSig === '') {
    http_response_code(500);
    echo 'No public signature';
    exit;
}

$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
$selfUrl = $scheme . '://' . $host . '/api/tournament/publish_card_public.php?sid=' . rawurlencode($sid);

$imgUrl = $scheme . '://' . $host . '/api/tournament/publish_image_public.php'
    . '?sid=' . rawurlencode($sid)
    . '&file=' . rawurlencode($cover)
    . '&exp=' . $publicExp
    . '&sig=' . rawurlencode($publicSig)
    . '&v=' . (int)time(); // только для тестов (VK кеширует люто)

$desc = trim(preg_replace('~\s+~u', ' ', $text));
if (function_exists('mb_strlen') && mb_strlen($desc, 'UTF-8') > 180) {
    $desc = mb_substr($desc, 0, 180, 'UTF-8') . '…';
}

function h(string $s): string {
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store');
header('X-Robots-Tag: noindex, nofollow');

?>
<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title><?=h($title)?></title>

  <meta property="og:type" content="article" />
  <meta property="og:title" content="<?=h($title)?>" />
  <meta property="og:description" content="<?=h($desc)?>" />
  <meta property="og:url" content="<?=h($selfUrl)?>" />

  <meta property="og:image" content="<?=h($imgUrl)?>" />
  <meta property="og:image:secure_url" content="<?=h($imgUrl)?>" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image" content="<?=h($imgUrl)?>" />
</head>
<body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial; padding:16px;">
  <h3 style="margin:0 0 12px;"><?=h($title)?></h3>
  <div style="white-space:pre-line; opacity:.85;"><?=h($text)?></div>

  <!-- чисто чтобы руками удобно тестить -->
  <p style="margin-top:16px; opacity:.65;">
    image: <a href="<?=h($imgUrl)?>" target="_blank" rel="noopener">open</a>
  </p>
</body>
</html>
