<?php
declare(strict_types=1);

require __DIR__ . '/_bootstrap.php';
require_role('organizer');

try {
  $pdo = db();

  // ensure settings table (MySQL)
  $pdo->exec("
    CREATE TABLE IF NOT EXISTS settings (
      k VARCHAR(64) NOT NULL PRIMARY KEY,
      v TEXT NOT NULL,
      updated_at DATETIME NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  ");

  // read JSON body
  $raw = file_get_contents('php://input');
  $data = json_decode($raw ?: '[]', true);
  if (!is_array($data)) {
    http_response_code(400);
    respond_json(['ok'=>false,'error'=>'Bad JSON body']);
    exit;
  }

  $k = (string)($data['k'] ?? '');
  $value = $data['value'] ?? null;

  if ($k === '') {
    http_response_code(400);
    respond_json(['ok'=>false,'error'=>'Bad value','details'=>'Поле k обязательно']);
    exit;
  }

  // allow only known keys (строго)
  if (!in_array($k, ['publish_footer', 'snapshots_keep_days'], true)) {
    http_response_code(400);
    respond_json(['ok'=>false,'error'=>'Bad value','details'=>'Недопустимый ключ настройки']);
    exit;
  }

  // ---- snapshots_keep_days ----
  if ($k === 'snapshots_keep_days') {
    $n = null;
    if (is_int($value)) $n = $value;
    else if (is_string($value) || is_float($value) || is_bool($value)) $n = (int)$value;

    if ($n === null) {
      http_response_code(400);
      respond_json(['ok'=>false,'error'=>'Bad value','details'=>'Поле value должно быть числом']);
      exit;
    }

    if ($n < 1) $n = 1;
    if ($n > 365) $n = 365;

    $stmt = $pdo->prepare("INSERT INTO settings (k,v,updated_at)
                           VALUES (:k,:v,NOW())
                           ON DUPLICATE KEY UPDATE v=VALUES(v), updated_at=VALUES(updated_at)");
    $stmt->execute([':k'=>$k, ':v'=>(string)$n]);

    respond_json(['ok'=>true,'k'=>$k,'value'=>$n]);
    exit;
  }

  // ---- publish_footer ----
  if (!is_array($value)) {
    http_response_code(400);
    respond_json(['ok'=>false,'error'=>'Bad value','details'=>'Поле value должно быть объектом']);
    exit;
  }

  // helpers
  $toBool = function($x): bool {
    if (is_bool($x)) return $x;
    if (is_int($x)) return $x !== 0;
    $s = trim((string)$x);
    if ($s === '') return false;
    return !in_array(mb_strtolower($s, 'UTF-8'), ['0','false','no','off','нет'], true);
  };

  $toInt = function($x, int $min, int $max, int $def): int {
    if ($x === null || $x === '') return $def;
    $s = str_replace(',', '.', trim((string)$x));
    if (!preg_match('/^-?\d+(?:\.\d+)?$/', $s)) return $def;
    $n = (int)round((float)$s);
    if ($n < $min) $n = $min;
    if ($n > $max) $n = $max;
    return $n;
  };

  $toFloat01 = function($x, float $def): float {
    if ($x === null || $x === '') return $def;
    $s = str_replace(',', '.', trim((string)$x));
    if (!preg_match('/^-?\d+(?:\.\d+)?$/', $s)) return $def;
    $n = (float)$s;
    if (!is_finite($n)) return $def;
    if ($n < 0) $n = 0;
    if ($n > 1) $n = 1;
    return (float)number_format($n, 3, '.', '');
  };

  $toStr = function($x, int $maxLen, string $def): string {
    if ($x === null) return $def;
    $s = trim((string)$x);
    if ($s === '') return $def;
    if (mb_strlen($s, 'UTF-8') > $maxLen) {
      $s = mb_substr($s, 0, $maxLen, 'UTF-8');
    }
    return $s;
  };

  $out = [
    'enabled'   => $toBool($value['enabled'] ?? true),
    'text'      => $toStr($value['text'] ?? 'Generated by LazaCupSystem', 120, 'Generated by LazaCupSystem'),
    'dt_format' => $toStr($value['dt_format'] ?? 'Y-m-d H:i', 64, 'Y-m-d H:i'),
    'size'      => $toInt($value['size'] ?? 18, 8, 64, 18),
    'pad_x'     => $toInt($value['pad_x'] ?? 48, 0, 300, 48),
    'pad_y'     => $toInt($value['pad_y'] ?? 26, 0, 300, 26),
    'opacity'   => $toFloat01($value['opacity'] ?? 0.7, 0.7),
  ];

  if ($out['dt_format'] === '') $out['dt_format'] = 'Y-m-d H:i';

  $json = json_encode($out, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
  if ($json === false) {
    http_response_code(500);
    respond_json(['ok'=>false,'error'=>'Encode failed']);
    exit;
  }

  $stmt = $pdo->prepare("INSERT INTO settings (k,v,updated_at)
                         VALUES (:k,:v,NOW())
                         ON DUPLICATE KEY UPDATE v=VALUES(v), updated_at=VALUES(updated_at)");
  $stmt->execute([':k'=>$k, ':v'=>$json]);

  respond_json(['ok'=>true,'k'=>$k,'value'=>$out]);

} catch (Throwable $e) {
  http_response_code(500);
  respond_json(['ok'=>false,'error'=>'Server error','details'=>$e->getMessage()]);
}
