<?php
declare(strict_types=1);

require __DIR__ . '/_bootstrap.php';
require_role('organizer','operator');

try {
  $pdo = db();

  $k = trim((string)($_GET['k'] ?? 'publish_footer'));
  if ($k === '') $k = 'publish_footer';

  // разрешённые ключи (строго)
  $allowed = ['publish_footer', 'snapshots_keep_days'];
  if (!in_array($k, $allowed, true)) {
    respond_json(['ok'=>false,'error'=>'Bad key'], 400);
  }

  // publish_footer (JSON object)
  if ($k === 'publish_footer') {
    $raw = lc_setting_get($pdo, $k);
    $j = $raw ? json_decode($raw, true) : null;

    if (!is_array($j)) {
      $j = [
        'enabled'   => true,
        'text'      => 'Generated by LazaCupSystem',
        'dt_format' => 'Y-m-d H:i',
        'size'      => 18,
        'pad_x'     => 48,
        'pad_y'     => 26,
        'opacity'   => 0.70,
      ];
    }

    respond_json(['ok'=>true,'k'=>$k,'value'=>$j]);
  }

  // snapshots_keep_days (int)
  $raw = lc_setting_get($pdo, $k);
  $n = (int)trim((string)$raw);
  if ($n < 1 || $n > 365) $n = 14;

  respond_json(['ok'=>true,'k'=>$k,'value'=>$n]);

} catch (Throwable $e) {
  respond_json(['ok'=>false,'error'=>$e->getMessage()], 500);
}
